### PR TITLE
Components Updated 

### PR DESCRIPTION
**Pull request by pratiyushmishra7**

### CODE REVIEW

**Comment by Atishya-jain** [comment]
Screenshot from 2019-07-05 23-23-33
I got this error on npm install

**Comment by Atishya-jain** [comment]
Screenshot from 2019-07-05 23-22-52
And this on running the app.
Something with the dependencies or their version is not correct.

**Comment by pratiyushmishra7** [comment]
i am guessing some of the files i installed i may have forgot to use --save so they are not installed while u did npm install thats why the second error is coming.I am clueless about the first one though.Let me rectify the second one and lets see then.

**Comment by Atishya-jain** [comment]
Yes, Clone a fresh repository and then try to set it up.
You may be able to correct it if there are no global dependencies

**Pull request merged**
